channels:
- conda-forge
dependencies:
- pyiron_base =0.6.8
- pyiron_atomistics =0.2.67
- pyiron_contrib =0.1.10
- pyiron_data =0.0.22
- maxvolpy =0.3.8
- seaborn >=0.12
- scikit-learn >=1
- tqdm
- numpy
- matplotlib
- scipy
